version: '3.8'

services:
  backend:
    build: ./backend
    container_name: edupath-backend
    ports:
      - "8081:8080" # Mapping to 8081 to avoid conflict if gateway uses 8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/edupath?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - edupath-net

  gateway:
    build: ./gateway
    container_name: edupath-gateway
    ports:
      - "8080:8080"
    environment:
      - BACKEND_URI=http://backend:8080
      - ML_URI=http://ml:8000
    depends_on:
      - backend
      - ml
    networks:
      - edupath-net

  frontendweb:
    build: ./frontendweb
    container_name: edupath-frontend
    ports:
      - "5173:80"
    networks:
      - edupath-net

  ml:
    build: ./machine_learning
    container_name: edupath-ml
    ports:
      - "8000:8000"
    networks:
      - edupath-net

  db:
    image: mysql:8.0
    container_name: edupath-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=edupath
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - edupath-net

networks:
  edupath-net:
    driver: bridge

volumes:
  db_data:
